name 'ohai-triton'
maintainer 'Coy Hile'
maintainer_email 'coy.hile@coyhile.com'
source_url 'https://github.com/coyhile/ohai-triton'
issues_url 'https://github.com/coyhile/ohai-triton/issues'
license 'MPL-2.0'
description 'ohai plugins for Joyent Triton Datacenter'
long_description 'ohail plugins for Joyent Triton Datacenter'
version '1.0.0'

chef_version '>= 12.0'

supports 'redhat'
supports 'centos'
supports 'ubuntu'
supports 'smartos'
supports 'windows'

depends 'ohai'
depends 'chef-sugar'
